### ISSUE TITLE
onScroll for individual collection

### ISSUE THREAD

**Issue by JanRajtr** [apptekstudios/ASCollectionView#136]
Hi,

**Description**
Current implementation of `onScroll` method register scrolling only in parent TableView. There is probably no way how to handle scroll of individual collection view within the ASCollectionView.

**To Reproduce**
Steps to reproduce the behaviour:

1. Make simple one level ASCollectionView with `ASCollectionView(data: _, dataID: _  ) { ...}`
2. Register `onScroll` method
3. Expect callback called on scroll.

**Expected behaviour**
It would be really helpful if there would be possible to have this `onScroll` method also for child collectionViews. Imho implementation e.g. own scrolling indicators is impossible now due to this.

**Comment by apptekstudios** [comment]
Unfortunately this is a limitation of the underlying UICollectionViewCompositionalLayout. You could try nesting ASCollectionViews within an ASTableView. Alternatively other custom UICollectionViewLayout classes might offer better scroll-handling support

**Comment by apptekstudios** [comment]
There’s a few stack overflow discussions on the topic (re didScroll and UICollectionViewCompositionalLayout) if you wanted to investigate further :)

**Comment by apptekstudios** [comment]
It turns out you can provide a closure for the `NSCollectionLayoutSectionVisibleItemsInvalidationHandler` (when you define your layout) that is called on scrolling the nested scrollViews, with the offset for that section 🎉 

https://developer.apple.com/documentation/uikit/nscollectionlayoutsection/3199096-visibleitemsinvalidationhandler

Note that it is called not only when scrolling, but also at other times:

> The handler is called before each layout cycle, any time an animation occurs in that section due to changes such as adding or removing items, scrolling the section, or rotating the device.

**Comment by JanRajtr** [comment]
Cool, thanks! :)
