### ISSUE TITLE
NavigationLink not working on section headers and footers

### ISSUE THREAD

**Issue by sthwicked** [apptekstudios/ASCollectionView#185]
**Describe the bug**
When I wrap my section header view in a navigation link, no navigation is executed when the conditions are met

**To Reproduce**
ASCollectionViewSection(...)
.sectionHeader {
NavigationLink(...) {
HeaderView()
}
}

**Xcode Version:**
- 

**Simulator, Device, Both?**
- both

**Comment by Carterman1** [comment]
Im having this problem too

**Comment by seboslaw** [comment]
+1

**Comment by paulfreeman** [comment]
I would not expect this to work,  It is a feature rather than a bug.  A solution is to embed the CollectionView in a UIKit UINavigationController and then implement navigations using UIKit.  If trying to use SwiftUI's NavigationLink, it will effectively be isolated in a UIHostingController vended UIViewController and there's no way to use that to trigger navigations because SwiftUI will not build the appropriate runtime model which has to be 'predefined' ahead of data source resolution. I only know this because I was trying to design a similar SwiftUI wrapper prior to finding this library.

**Comment by apptekstudios** [comment]
Unfortunately, SwiftUI isn't recognising navigation links when they are wrapped within UIKit elements. Without apple exposing some of their private APIs I can't get around this within the library itself.

There are some useful ideas on this blog (https://fivestars.blog/swiftui/programmatic-navigation.html) - he suggests how to use a single navigation link (which would be outside of the ASCollectionView) to handle all the necessary navigations. With this you should be able to achieve what you want 😄
