### ISSUE TITLE
Fatal error: Can't form Range with upperBound < lowerBound

### ISSUE THREAD

**Issue by janandre** [apptekstudios/ASCollectionView#23]
**Error:** Can't form Range with upperBound < lowerBound
**XCode Version:** Version 11.2 beta (11B41)

Occurs when reloading SwiftUI view VERY fast.
Create a button that is reloading the collection view with changing amount of items.
Click that button very fast.

I admit this is an unusal user interaction but as it reloads on changes in Combine those could fire more often for some setups.

In my setup this is not a big problem as the button is inside a popover and that will disappear after one click. I just wanted to challenge the reloading 🤓 

<img width="1143" alt="Bildschirmfoto 2019-10-21 um 20 04 05" src="https://user-images.githubusercontent.com/9200290/67230804-4b4d0800-f43e-11e9-98c7-a3f78a8083f8.png">

**Comment by apptekstudios** [comment]
When you  get a chance could you please test this using the dev branch. https://github.com/apptekstudios/ASCollectionView/tree/dev

I think the culprit is `suffix(from:)` not being bounds safe - so I reworked the prefetching code to use subscripts. Hopefully that has fixed this error! I don't have a test project at the moment that can reproduce it, so please let me know if it is indeed fixed 🙂

**Comment by apptekstudios** [comment]
@janandre Is this resolved for you in the latest release?

I didn’t manage to reproduce the crash in any of my test projects, so haven’t been able to check whether the changes have indeed fixed the issue.

**Comment by janandre** [comment]
Seems resolved! If I reload very quickly I don't get crashes!
