### ISSUE TITLE
How to initialise ASCollectionView with FetchedResults from a @FetchRequest?

### ISSUE THREAD

**Issue by magnas35** [apptekstudios/ASCollectionView#62]
When I supply my FetchedResults to the `data` parameter of the initialisation method I get "Cannot convert value of type 'FetchedResults<Place>' to expected argument type '[_]'"

Is there a way to feed the ASCollectionView with my managedObjects directly? I'm currently working around the problem with an array of data (maintained in parallel with the fetchedResults) limited to visible cell content. This is unpleasant.

Great work on this!

**Comment by apptekstudios** [comment]
Thanks for posting the issue @magnas35 :) 

This was happening because ASCollectionView was expecting an Array, and FetchedResults is a different type of sequence. I've now implemented support for RandomAccessCollection (which FetchedResults conforms to) [in this branch](https://github.com/apptekstudios/ASCollectionView/tree/onReachedBoundary).

If you use that branch instead it should hopefully work! 😄(you can select branch instead of version when adding a package to the xcodeproj)
(I haven't tested as I don't have a coreData test case at the moment, but will hopefully put one together soon)

**Comment by apptekstudios** [comment]
Those changes are now in the master, release V1.2 🎉 Please let me know if you can now use `FetchedResults` directly :)

**Comment by magnas35** [comment]
Swapped in my FetchedResults and works like a charm. Many thanks!
