### ISSUE TITLE
Crash when using .sectionFooter

### ISSUE THREAD

**Issue by ryangittings** [apptekstudios/ASCollectionView#70]
Hey,

Receiving the following crash when initialising the ASCollectionView with the following:

`ASCollectionView(sections: self.sections).layout(self.layout)`, which causes the following:

`Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'could not dequeue a view of kind: UICollectionElementKindSectionFooter with identifier 42E2D4F8-919E-4EFD-9E98-7803857EFA55 - must register a nib or a class for the identifier or connect a prototype cell in a storyboard'`. 

Only seems to happen with that type of initialisation as the demo apps work?

**Comment by apptekstudios** [comment]
I think I've figured this one out. The supplementaries were being registered on the initial setup of the data source, but it wasn't checking if any new ones had been requested since - its possible this edge case was occuring.

Try the `dev` branch and it should work now if that was the cause. I don't have a demo that reproduces it though so couldn't actually check 👍

**Comment by ryangittings** [comment]
Nice, that works! 💃
