### ISSUE TITLE
Feature: access itemSize in ASCollectionView.Coordinator extension

### ISSUE THREAD

**Issue by DanielLeberle** [apptekstudios/ASCollectionView#82]
Hi everyone,

I don't have a bug but rather a question regarding the implementation and access to the layouts `itemSize` property:
I cloned the repo in order to implement a snapping behaviour by adding  `scrollViewWillEndDragging` right below `scrollViewDidScroll` to the `ASCollectionView.Coordinator` extension and it works as expected with static values for the `itemSize` and `spacing`. Since I use ASCollectionView in several Views where I have different values for `itemSize` and `spacing`, I would like to access these values given to the layout somehow. Can you give me a hint on how to access them? Thank you!

**Comment by apptekstudios** [comment]
Which layout class are you using? Is it a UICVFlowLayout?

Also, take a look at the MagazineLayout in the demo project - it shows how you can subclass (from ASCollectionViewDelegate)  and use a custom delegate without needing to modify the project 😄

**Comment by DanielLeberle** [comment]
Hi, thanks for your reply!

I'm using the list layout with only one section and a horizontal direction.

**Comment by apptekstudios** [comment]
It’s worth checking out the orthogonal scrolling support in UICollectionViewCompositionalLayout as it can automatically give you paging behaviour. See the AppStore page in the demo app. Or [see this blog post for an example](https://dev.to/kevinmaarek/replicating-the-appstore-s-collectionviewlayout-orthogonal-in-swift-5-42je)

Because of the way UICollectionViewCompositionalLayout it’s very difficult to extract the item size unfortunately.
