### ISSUE TITLE
Pagination with ASCollectionView

### ISSUE THREAD

**Issue by Rahul379** [apptekstudios/ASCollectionView#92]
How to enable pagination with ASCollectionView. Need to integrate page control.

**To Reproduce**
Not getting any documentation for enabling pagination.

**Expected behaviour**
Way to enable pagination and integrate page controller.

**Xcode Version:**
- 11.3.1

**Simulator, Device, Both?**
- Both

**Comment by apptekstudios** [comment]
If you're using a compositional layout, check out the WWDC videos on the built-in paging support for orthogonal grids - might be helpful.

Otherwise, the way to achieve this behaviour would be to use a custom collectionView delegate. See the `MagazineLayout` demo for an example of a custom delegate. The delegate function of interest would be `scrollViewWillEndDragging` which lets you determine where to snap scrolling to when the touch is released.
